-- CreateTable
CREATE TABLE "Client" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "phone" STRING NOT NULL,
    "name" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Client_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Product" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "price" DECIMAL(65,30) NOT NULL,
    "product" STRING NOT NULL,
    "brand" STRING NOT NULL,
    "size" STRING NOT NULL,
    "color" STRING NOT NULL,
    "providerId" INT4 NOT NULL,
    "description" STRING,
    "entry" TIMESTAMP(3) NOT NULL,
    "sellId" INT4,
    "sellPrice" DECIMAL(65,30),

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Sell" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" STRING NOT NULL,
    "buyerId" INT4 NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Sell_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Product_providerId_idx" ON "Product"("providerId");

-- CreateIndex
CREATE INDEX "Product_sellId_idx" ON "Product"("sellId");

-- CreateIndex
CREATE INDEX "Sell_buyerId_idx" ON "Sell"("buyerId");
